#! /bin/sh
# script uses gdalwarp to create mosaic  with 90KM resolution 
# using ASTER GDEM tiles adjacent to 60 Degrees North Latitude.
# Author: Rick Reeves, NCEAS April 26, 2011
date
rm /data/project/organisms/rcr/AsterCgiarMerge/mergeCgiarAsterBdyASTER_BL.tif
gdalwarp -of GTiff -ot Int16 -tr .0008333 .0008333 -r bilinear \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W101_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W102_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W103_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W104_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W105_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W106_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W107_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W108_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W109_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W110_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W111_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W112_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W113_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W114_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W115_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W116_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W117_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W118_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W119_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W120_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W121_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W122_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W123_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W124_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W125_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W126_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W127_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W128_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W129_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W130_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W131_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W132_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W133_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W134_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W135_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W136_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W137_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W138_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W139_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N60W140_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W101_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W102_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W103_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W104_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W105_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W106_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W107_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W108_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W109_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W110_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W111_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W112_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W113_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W114_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W115_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W117_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W118_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W119_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W120_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W121_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W122_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W123_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W124_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W125_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W126_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W127_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W128_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W129_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W130_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W131_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W132_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W133_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W134_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W135_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W136_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W137_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W138_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W139_dem.tif \
/data/project/organisms/rcr/ASTERNorthernHemi/ASTGTM_N61W140_dem.tif \
/data/project/organisms/rcr/AsterCgiarMerge/mergeCgiarAsterBdyASTER_BL.tif
date
